/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiIndexRouteImport } from './routes/ui/index'
import { Route as UiSplatRouteImport } from './routes/ui/$'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiIndexRoute = UiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UiRoute,
} as any)
const UiSplatRoute = UiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => UiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui': typeof UiRouteWithChildren
  '/ui/$': typeof UiSplatRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui/$': typeof UiSplatRoute
  '/ui': typeof UiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui': typeof UiRouteWithChildren
  '/ui/$': typeof UiSplatRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ui' | '/ui/$' | '/ui/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ui/$' | '/ui'
  id: '__root__' | '/' | '/ui' | '/ui/$' | '/ui/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiRoute: typeof UiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/': {
      id: '/ui/'
      path: '/'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexRouteImport
      parentRoute: typeof UiRoute
    }
    '/ui/$': {
      id: '/ui/$'
      path: '/$'
      fullPath: '/ui/$'
      preLoaderRoute: typeof UiSplatRouteImport
      parentRoute: typeof UiRoute
    }
  }
}

interface UiRouteChildren {
  UiSplatRoute: typeof UiSplatRoute
  UiIndexRoute: typeof UiIndexRoute
}

const UiRouteChildren: UiRouteChildren = {
  UiSplatRoute: UiSplatRoute,
  UiIndexRoute: UiIndexRoute,
}

const UiRouteWithChildren = UiRoute._addFileChildren(UiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiRoute: UiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
